# Generated by Django 4.1 on 2022-08-23 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='geeks_field',
            field=models.FileField(default='', upload_to='Uploaded Files/'),
        ),
    ]
