# Generated by Django 4.1 on 2022-08-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_document_geeks_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='geeks_field',
        ),
    ]
