# Generated by Django 4.1 on 2022-08-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_remove_document_geeks_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='namebd',
            field=models.FileField(default=1, upload_to='db_files/'),
            preserve_default=False,
        ),
    ]
