# Generated by Django 4.1 on 2022-08-25 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_document_namebd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='namebd',
        ),
        migrations.AddField(
            model_name='document',
            name='databasename',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
