# Generated by Django 4.1 on 2022-08-25 13:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_remove_document_namebd_document_databasename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='document',
            old_name='databasename',
            new_name='databasename1',
        ),
    ]
